// AUTO-GENERATED by scripts/train.ts — do not edit by hand.
// Trained on the deterministic synthetic dataset (seed 42, n=2000).

import type { ModelArtifact } from "./model";

export const MODEL_ARTIFACT: ModelArtifact = {
  "trainedAt": "2026-07-05T16:39:28.697Z",
  "seed": 42,
  "n": 2000,
  "pillars": {
    "businessVitality": {
      "features": [
        "turnover6moTrend",
        "turnoverCAGR",
        "turnoverVolatilityCV",
        "invoiceCountTrend",
        "seasonalityIndex"
      ],
      "means": [
        0.002422,
        0.004766,
        0.189054,
        0.00034,
        0.170712
      ],
      "stds": [
        0.05958,
        0.048446,
        0.084284,
        0.096378,
        0.083786
      ],
      "weights": [
        -0.102019,
        0.191645,
        -0.473678,
        0.099116,
        -0.387857
      ],
      "bias": 0.009117,
      "platt": null
    },
    "cashflowHealth": {
      "features": [
        "avgMonthlyNetInflow",
        "inflowVolatilityCV",
        "runwayMonths",
        "negativeBalanceDays",
        "dscrProxy"
      ],
      "means": [
        -0.718356,
        0.205217,
        8.885024,
        0.354884,
        1.566346
      ],
      "stds": [
        1.834788,
        0.082194,
        11.225753,
        0.366304,
        2.154302
      ],
      "weights": [
        0.03293,
        -0.470882,
        0.421186,
        -0.201006,
        -0.154336
      ],
      "bias": 0.040873,
      "platt": null
    },
    "formalisationCompliance": {
      "features": [
        "gstOnTimeFilingPct",
        "monthsFiledOverMonthsActive",
        "epfoActiveFlag",
        "epfoContributionConsistency"
      ],
      "means": [
        0.627611,
        0.607143,
        0.693,
        0.627754
      ],
      "stds": [
        0.227685,
        0.24542,
        0.461249,
        0.166619
      ],
      "weights": [
        0.560817,
        -0.300409,
        -0.087963,
        0.311257
      ],
      "bias": 0.047177,
      "platt": {
        "a": 1.034151,
        "b": 0.008029
      }
    },
    "bankingBehaviour": {
      "features": [
        "bounceRate",
        "avgBalanceBuffer",
        "balanceStabilityCV",
        "minBalanceEventCount"
      ],
      "means": [
        0.094726,
        1.250306,
        0.968735,
        0.358072
      ],
      "stds": [
        0.132508,
        1.600875,
        0.878222,
        0.364818
      ],
      "weights": [
        -0.135261,
        0.543495,
        0.117827,
        -0.407818
      ],
      "bias": 0.059091,
      "platt": null
    },
    "obligationsLeverage": {
      "features": [
        "obligationToInflowRatio",
        "obligationCount"
      ],
      "means": [
        0.210235,
        2.1745
      ],
      "stds": [
        0.096351,
        1.191239
      ],
      "weights": [
        -0.776799,
        -0.205869
      ],
      "bias": 0.040067,
      "platt": null
    }
  }
};
