// Train the five pillar logistic regressions on the synthetic dataset and emit
// scoring/model-artifact.generated.ts.
//
// Per the methodology: final coefficients are fit on the FULL set; the 80/20
// split is used only to decide whether Platt recalibration lowers a pillar's
// held-out ECE. Run with:  pnpm --filter @workspace/api-server run train
//
// This script never touches Postgres — the dataset is regenerated deterministically.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { generateDataset } from "../synthetic/generate";
import { computeFeatures } from "../features";
import { PILLARS, PILLAR_ORDER, type FeatureVector } from "../features/catalog";
import {
  fitStandardizer,
  standardizeRow,
  fitLogReg,
  fitPlatt,
  linear,
  sigmoid,
  applyPlatt,
} from "../ml";
import { ece } from "../ml/metrics";
import type { ModelArtifact, PillarModel } from "../scoring/model";

const SEED = 42;
const N = 2000;
const TRAIN_FRACTION = 0.8;

function rowFor(features: FeatureVector, keys: readonly string[]): number[] {
  return keys.map((k) => features[k as keyof FeatureVector]);
}

function main(): void {
  const dataset = generateDataset({ n: N, seed: SEED });
  const featureRecords = dataset.map((b) => computeFeatures(b));
  const labels = dataset.map((b) => b.master.outcomeLabel);

  const nTrain = Math.floor(N * TRAIN_FRACTION);
  const pillars = {} as ModelArtifact["pillars"];

  for (const id of PILLAR_ORDER) {
    const meta = PILLARS[id];
    const keys = meta.features;
    const rawRows = featureRecords.map((fr) => rowFor(fr.features, keys));

    // Final coefficients: standardizer + weights fit on the FULL set.
    const std = fitStandardizer(rawRows);
    const stdRows = rawRows.map((r) => standardizeRow(r, std));
    const model = fitLogReg(stdRows, labels, { lr: 0.2, epochs: 600, l2: 1e-3 });

    // Platt decision: measure held-out ECE raw vs. Platt-calibrated.
    const heldLogits = stdRows.slice(nTrain).map((r) => linear(model, r));
    const heldLabels = labels.slice(nTrain);
    const trainLogits = stdRows.slice(0, nTrain).map((r) => linear(model, r));
    const trainLabels = labels.slice(0, nTrain);

    const rawEce = ece(heldLogits.map(sigmoid), heldLabels);
    const platt = fitPlatt(trainLogits, trainLabels);
    const calEce = ece(heldLogits.map((z) => applyPlatt(platt, z)), heldLabels);
    const usePlatt = calEce + 1e-4 < rawEce;

    const round = (x: number) => Number(x.toFixed(6));
    const pillarModel: PillarModel = {
      features: [...keys],
      means: std.means.map(round),
      stds: std.stds.map(round),
      weights: model.weights.map(round),
      bias: round(model.bias),
      platt: usePlatt ? { a: round(platt.a), b: round(platt.b) } : null,
    };
    pillars[id] = pillarModel;

    console.log(
      `${meta.label.padEnd(28)} platt=${usePlatt ? "yes" : "no "} ` +
        `ece raw=${rawEce.toFixed(3)} cal=${calEce.toFixed(3)}`,
    );
  }

  const artifact: ModelArtifact = {
    trainedAt: new Date().toISOString(),
    seed: SEED,
    n: N,
    pillars,
  };

  const outPath = path.resolve(
    path.dirname(fileURLToPath(import.meta.url)),
    "../scoring/model-artifact.generated.ts",
  );
  const body = `// AUTO-GENERATED by scripts/train.ts — do not edit by hand.
// Trained on the deterministic synthetic dataset (seed ${SEED}, n=${N}).

import type { ModelArtifact } from "./model";

export const MODEL_ARTIFACT: ModelArtifact = ${JSON.stringify(artifact, null, 2)};
`;
  writeFileSync(outPath, body);
  console.log(`\nWrote ${outPath}`);
}

main();
