// Score every synthetic MSME against its known outcome_label and report
// discrimination + calibration, split into the 20% Platt-decision held-out slice
// and the full set. Run with:
//   pnpm --filter @workspace/api-server run validate
//
// NOTE: outcome_label is generated by the same latent process as the features,
// so these numbers validate that the pipeline recovers a planted synthetic
// signal — NOT that it predicts real-world MSME default.

import { generateDataset } from "../synthetic/generate";
import { computeFeatures } from "../features";
import { PILLARS, PILLAR_ORDER } from "../features/catalog";
import { MODEL_ARTIFACT } from "../scoring/model-artifact.generated";
import { evaluatePillar } from "../scoring/model";
import { scoreFeatures } from "../scoring/score";
import { sustainableEmi } from "../scoring/repayment";
import { auc, brier, ece, accuracyAt } from "../ml/metrics";

const SEED = 42;
const N = 2000;
const TRAIN_FRACTION = 0.8;

interface Row {
  label: string;
  n: number;
  auc: number;
  brier: number;
  ece: number;
  acc: number;
}

function metricsRow(label: string, probs: number[], labels: number[]): Row {
  return {
    label,
    n: probs.length,
    auc: auc(probs, labels),
    brier: brier(probs, labels),
    ece: ece(probs, labels),
    acc: accuracyAt(probs, labels),
  };
}

function printTable(rows: Row[]): void {
  const head =
    "| Metric".padEnd(38) +
    "| n    | AUC   | Brier | ECE   | Acc@0.5 |";
  console.log(head);
  console.log("|" + "-".repeat(head.length - 1));
  for (const r of rows) {
    console.log(
      `| ${r.label}`.padEnd(38) +
        `| ${String(r.n).padEnd(4)} | ${r.auc.toFixed(3)} | ${r.brier.toFixed(3)} | ${r.ece.toFixed(3)} | ${r.acc.toFixed(3)}   |`,
    );
  }
}

function main(): void {
  const dataset = generateDataset({ n: N, seed: SEED });
  const featureRecords = dataset.map((b) => computeFeatures(b));
  const labels = dataset.map((b) => b.master.outcomeLabel);
  const nTrain = Math.floor(N * TRAIN_FRACTION);

  const heldSlice = <T>(xs: T[]) => xs.slice(nTrain);

  const rows: Row[] = [];

  // Per-pillar
  for (const id of PILLAR_ORDER) {
    const meta = PILLARS[id];
    const model = MODEL_ARTIFACT.pillars[id];
    const probs = featureRecords.map((fr) => evaluatePillar(model, fr.features).probability);
    rows.push(metricsRow(`${meta.label} (held-out)`, heldSlice(probs), heldSlice(labels)));
    rows.push(metricsRow(`${meta.label} (full set)`, probs, labels));
  }

  // Overall blended score, read as a probability via overallScore/100.
  const overallProbs = featureRecords.map((fr, i) => {
    const rep = sustainableEmi(dataset[i]!.transactions);
    return scoreFeatures(fr, rep).overallScore / 100;
  });
  rows.push(metricsRow("Overall score (held-out)", heldSlice(overallProbs), heldSlice(labels)));
  rows.push(metricsRow("Overall score (full set)", overallProbs, labels));

  printTable(rows);

  const defaultRate = labels.filter((l) => l === 0).length / labels.length;
  console.log(`\nDataset: n=${N}, seed=${SEED}, default rate=${(defaultRate * 100).toFixed(1)}%`);
  console.log(
    "Reminder: synthetic self-recovery, not real-world default prediction.",
  );
}

main();
